### ISSUE TITLE
Failed to parse block error.

### ISSUE THREAD

**Issue by Integrative** [PoC-Consortium/burstcoin#181]
Fresh install, new sync, getting frequent errors like below,

Client seems to be working though.

[```
INFO] 2018-03-17 06:52:50 brs.BlockchainProcessorImpl - Failed to parse block trace: [Ljava.lang.StackTraceElement;@6eabaeab
[INFO] 2018-03-17 06:52:54 brs.BlockchainProcessorImpl - Failed to parse block: {}java.lang.NullPointerException
java.lang.NullPointerException
	at brs.services.impl.BlockServiceImpl.calculateBaseTarget(BlockServiceImpl.java:240)
	at brs.BlockchainProcessorImpl$1.run(BlockchainProcessorImpl.java:445)
	at brs.util.ThreadPool.lambda$start$0(ThreadPool.java:96)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[INFO] 2018-03-17 06:52:54 brs.BlockchainProcessorImpl - Failed to parse block trace: [Ljava.lang.StackTraceElement;@4346a31d****
```

**Comment by modislaszlo** [comment]
I'm getting the same issue:

[INFO] 2018-03-17 11:36:50 brs.BlockchainProcessorImpl - Failed to parse block: {}java.lang.NullPointerException
java.lang.NullPointerException
        at brs.services.impl.BlockServiceImpl.calculateBaseTarget(BlockServiceImpl.java:240)
        at brs.BlockchainProcessorImpl$1.run(BlockchainProcessorImpl.java:445)
        at brs.util.ThreadPool.lambda$start$0(ThreadPool.java:96)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

I'm using Windows 10 with maria db and is stuck at 468967 block. Not sure how to do pop-off without Qbundle and I don't have Qbundle

**Comment by captaincheckov** [comment]
fresh install und sync from scratch: same problem here on MAC with mariadb. popoff some blocks didnt help.

**Comment by ac0v** [comment]
could the ones, who have issue provide me a database dump?

**Comment by llybin** [comment]
fresh install, I tried to sync two times from a scratch, is reproduced.
synchronization is stuck in wallet.
I uploading a dump DB H2, I will provide u link.

`Mar 19 02:46:47 PE70 burst.sh[17865]: [SEVERE] 2018-03-19 02:46:47 brs.BlockchainProcessorImpl - Block not accepted
Mar 19 02:46:47 PE70 burst.sh[17865]: brs.BlockchainProcessor$TransactionNotAcceptedException: Double spending transaction: 766531839369755557 transaction: {"senderPublicKey":"59596e6cdf06499e40322d86d52ab849f>
Mar 19 02:46:47 PE70 burst.sh[17865]:         at brs.BlockchainProcessorImpl.accept(BlockchainProcessorImpl.java:978)
Mar 19 02:46:47 PE70 burst.sh[17865]:         at brs.BlockchainProcessorImpl.pushBlock(BlockchainProcessorImpl.java:950)
Mar 19 02:46:47 PE70 burst.sh[17865]:         at brs.BlockchainProcessorImpl.lambda$new$7(BlockchainProcessorImpl.java:270)
Mar 19 02:46:47 PE70 burst.sh[17865]:         at brs.util.ThreadPool.lambda$start$0(ThreadPool.java:96)
Mar 19 02:46:47 PE70 burst.sh[17865]:         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
Mar 19 02:46:47 PE70 burst.sh[17865]:         at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
Mar 19 02:46:47 PE70 burst.sh[17865]:         at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:300)
Mar 19 02:46:47 PE70 burst.sh[17865]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
Mar 19 02:46:47 PE70 burst.sh[17865]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
Mar 19 02:46:47 PE70 burst.sh[17865]:         at java.base/java.lang.Thread.run(Thread.java:844)`

`Mar 19 02:56:16 PE70 burst.sh[17865]: [INFO] 2018-03-19 02:56:16 brs.BlockchainProcessorImpl - Failed to parse block: {}java.lang.NullPointerException
Mar 19 02:56:16 PE70 burst.sh[17865]: java.lang.NullPointerException
Mar 19 02:56:16 PE70 burst.sh[17865]:         at brs.services.impl.BlockServiceImpl.calculateBaseTarget(BlockServiceImpl.java:240)
Mar 19 02:56:16 PE70 burst.sh[17865]:         at brs.BlockchainProcessorImpl$1.run(BlockchainProcessorImpl.java:445)
Mar 19 02:56:16 PE70 burst.sh[17865]:         at brs.util.ThreadPool.lambda$start$0(ThreadPool.java:96)
Mar 19 02:56:16 PE70 burst.sh[17865]:         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
Mar 19 02:56:16 PE70 burst.sh[17865]:         at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
Mar 19 02:56:16 PE70 burst.sh[17865]:         at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:300)
Mar 19 02:56:16 PE70 burst.sh[17865]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
Mar 19 02:56:16 PE70 burst.sh[17865]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
Mar 19 02:56:16 PE70 burst.sh[17865]:         at java.base/java.lang.Thread.run(Thread.java:844)`

**Comment by llybin** [comment]
dump DB H2: https://yadi.sk/d/oAlLyQbZ3TWNCo

**Comment by ChrisMaroglou** [comment]
Same issue here, version 2.1.0 using Windows 10, local MariaDB installation and downloaded blockchain from start. Attaching brs.log and link to mariadb sql dump.

[brs.log](https://github.com/PoC-Consortium/burstcoin/files/1824709/brs.log)

[MariaDB sql dump](https://drive.google.com/open?id=1Ylqd3Hk1w4R2yb-ZOxV-lZ3BOBTl1-b_)

**Comment by robwoodgate** [comment]
I was having this issue using the 2.1.0 branch, where wallet had got 'stuck' at a (presumably forked) block with above parse block error... but having just built 2.1.0 from master (with above fork handling improvements) the client raced past the fork and caught up no problems...

[INFO] 2018-03-21 11:31:04 brs.Burst - BRS 2.1.0 started successfully.
[WARNING] 2018-03-21 11:31:08 brs.BlockchainProcessorImpl - A fork is detected. Waiting for cache to be processed.
[WARNING] 2018-03-21 11:31:08 brs.BlockchainProcessorImpl - Cache is now processed. Starting to process fork.
[WARNING] 2018-03-21 11:31:15 brs.BlockchainProcessorImpl - Successfully switched to better chain.
[WARNING] 2018-03-21 11:31:15 brs.BlockchainProcessorImpl - Forkprocessing complete.

**Comment by Ready2Burst** [comment]
I have a related issue. My 2.0 wallet synced to block 470907 and then began failing on subsequent blocks:

> [INFO] 2018-03-20 00:18:20 brs.statistics.StatisticsManagerImpl - handling 3.01 blocks/s account cache hit ratio now/total:96.69%/97.23%
[INFO] 2018-03-20 00:18:29 brs.BlockchainProcessorImpl - processed block 470000
[INFO] 2018-03-20 01:13:15 brs.statistics.StatisticsManagerImpl - handling 0.15 blocks/s account cache hit ratio now/total:96.55%/97.23%
[WARNING] 2018-03-21 06:41:28 brs.BlockchainProcessorImpl - A fork is detected. Waiting for cache to be processed.
[WARNING] 2018-03-21 06:41:28 brs.BlockchainProcessorImpl - Cache is now processed. Starting to process fork.
[INFO] 2018-03-21 06:41:29 brs.services.impl.BlockServiceImpl - Error verifying block generation signature
java.lang.NullPointerException
        at brs.services.impl.BlockServiceImpl.verifyGenerationSignature(BlockServiceImpl.java:96)
        at brs.BlockchainProcessorImpl.pushBlock(BlockchainProcessorImpl.java:840)
        at brs.BlockchainProcessorImpl.access$800(BlockchainProcessorImpl.java:54)
        at brs.BlockchainProcessorImpl$1.processFork(BlockchainProcessorImpl.java:649)
        at brs.BlockchainProcessorImpl$1.run(BlockchainProcessorImpl.java:482)
        at brs.util.ThreadPool.lambda$start$0(ThreadPool.java:96)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
[WARNING] 2018-03-21 06:41:29 brs.BlockchainProcessorImpl - Forkprocessing complete.
[WARNING] 2018-03-21 06:41:35 brs.BlockchainProcessorImpl - A fork is detected. Waiting for cache to be processed.
[WARNING] 2018-03-21 06:41:35 brs.BlockchainProcessorImpl - Cache is now processed. Starting to process fork.
[INFO] 2018-03-21 06:41:35 brs.services.impl.BlockServiceImpl - Error verifying block generation signature
java.lang.NullPointerException
at brs.services.impl.BlockServiceImpl.verifyGenerationSignature(BlockServiceImpl.java:96)
        at brs.BlockchainProcessorImpl.pushBlock(BlockchainProcessorImpl.java:840)
        at brs.BlockchainProcessorImpl.access$800(BlockchainProcessorImpl.java:54)
        at brs.BlockchainProcessorImpl$1.processFork(BlockchainProcessorImpl.java:649)
        at brs.BlockchainProcessorImpl$1.run(BlockchainProcessorImpl.java:482)
        at brs.util.ThreadPool.lambda$start$0(ThreadPool.java:96)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

After a bunch of those, now I get:

> [INFO] 2018-03-21 06:51:55 brs.BlockchainProcessorImpl - Failed to parse block trace: [Ljava.lang.StackTraceElement;@606179b2
[INFO] 2018-03-21 06:51:57 brs.BlockchainProcessorImpl - Failed to parse block: {}java.lang.NullPointerException
java.lang.NullPointerException

**Comment by Integrative** [comment]
Now also getting this error.

```
[SEVERE] 2018-03-22 09:29:22 brs.BlockchainProcessorImpl - Uncaught exception in blockImporterThread
brs.Account$DoubleSpendingException: Unconfirmed exceeds confirmed balance or quantity for account 13383190289605706987
	at brs.Account.checkBalance(Account.java:297)
	at brs.Account.checkBalance(Account.java:302)
	at brs.services.impl.AccountServiceImpl.addToUnconfirmedBalanceNQT(AccountServiceImpl.java:231)
	at brs.TransactionType.undoUnconfirmed(TransactionType.java:269)
	at brs.services.impl.TransactionServiceImpl.undoUnconfirmed(TransactionServiceImpl.java:74)
	at brs.TransactionProcessorImpl.requeueAllUnconfirmedTransactions(TransactionProcessorImpl.java:336)
	at brs.BlockchainProcessorImpl.pushBlock(BlockchainProcessorImpl.java:956)
	at brs.BlockchainProcessorImpl.lambda$new$7(BlockchainProcessorImpl.java:270)
	at brs.util.ThreadPool.lambda$start$0(ThreadPool.java:96)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ChrisMaroglou** [comment]
After getting such errors, restarting the wallet seems to temporarily fix the problem for me and run fine for a few hours until they pop up again.

**Comment by bradfordcp** [comment]
I see the issue immediately after connecting to peers during startup:

```
[INFO] 2018-03-24 11:52:59 brs.Burst - BRS 2.0.0 started successfully.
[INFO] 2018-03-24 11:55:38 brs.peer.Peers - Finished connecting to 4 well known peers.
[INFO] 2018-03-24 11:55:38 brs.peer.Peers - You can open your Burst Wallet in your favorite browser with: http://127.0.0.1:8125 or http://localhost:8125
[SEVERE] 2018-03-24 11:55:54 brs.BlockchainProcessorImpl - Block not accepted
brs.BlockchainProcessor$TransactionNotAcceptedException: Double spending transaction: 9125369359307480244 transaction: {"senderPublicKey":"b6147da5da011100b715c8c055f550bcf624fe5a154d2d89e2df61e3a722fe46","signature":"b4185d2fa846b65d8a0a1788a1bf90b4cc3459c983dacdda02fe31d6e38d98012cef5e2790f26c95acd226bdab20cc8e0b225528716098ba4f7daddf59c623c6","feeNQT":100000000,"type":0,"version":1,"ecBlockId":"5392301306435585825","attachment":{},"subtype":0,"amountNQT":2177985226,"recipient":"4949543620935286908","ecBlockHeight":470565,"deadline":1440,"timestamp":113825857}
        at brs.BlockchainProcessorImpl.accept(BlockchainProcessorImpl.java:978)
        at brs.BlockchainProcessorImpl.pushBlock(BlockchainProcessorImpl.java:950)
        at brs.BlockchainProcessorImpl.lambda$new$7(BlockchainProcessorImpl.java:270)
        at brs.util.ThreadPool.lambda$start$0(ThreadPool.java:96)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[INFO] 2018-03-24 11:55:54 brs.BlockchainProcessorImpl - Failed to parse block: {}java.lang.NullPointerException
java.lang.NullPointerException
        at brs.services.impl.BlockServiceImpl.calculateBaseTarget(BlockServiceImpl.java:240)
        at brs.BlockchainProcessorImpl$1.run(BlockchainProcessorImpl.java:445)
        at brs.util.ThreadPool.lambda$start$0(ThreadPool.java:96)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[INFO] 2018-03-24 11:55:54 brs.BlockchainProcessorImpl - Failed to parse block trace: [Ljava.lang.StackTraceElement;@463f6f6
```

It's worth noting that `ecBlockHeight` is different when comparing my stacktrace with @Integrative

**Comment by Integrative** [comment]
pulled the latest codebase from master this morning in the hope something has been fixed, 
now wallet does not start at all anymore, giving the following error

```
Mar 26, 2018 8:23:33 AM brs.Burst validateVersionNotDev
SEVERE: THIS IS A DEVELOPMENT WALLET, PLEASE DO NOT USE THIS
```

**Comment by BurnMe2** [comment]
Hi,

i tried all BRS Wallets, but every Version doesn't work (on Linux)

BRS 2.0.0:
error message  Failed to parse block trace

BRS 2.0.1:
[INFO] 2018-03-26 08:45:13 brs.Burst - BRS 2.0.1 started successfully.
[SEVERE] 2018-03-26 08:45:39 brs.BlockchainProcessorImpl - Block not accepted

BRS 2.1.0:
the same error message like in BRS 2.0.1 "Block not accepted"

The Wallet 1.3.6cg is running stable on the same system.

I someone running the BRS Wallet stable with Linux ? How to fix the block not accepted error. I got the same issue on Wallet 1.2.8 but with 1.2.9 it has been fixed until the BRS Wallet.

**Comment by bradfordcp** [comment]
Which database are you using? I switched to MariaDB 10.2 in a container yesterday and successfully synced the entire blockchain on 2.0.0.

**Comment by BurnMe2** [comment]
Hi bradfordcp,

i am using Maria DB 10.2 too. I can sync the entire blockchain fully. But after syncing the blockchain the BRS Wallets is showing "Block not accepting" after some time and then after restart immediately. With the new 2.0.1 the parse thing is never shown again its always shown "block not accepted" now. So something has changed from 2.0.0 to 2.0.1 but its still not working for me. 

It's not stable when running over the long term. I hope that some developer can find the issue and fix it, or tell what to do. I am thinking they are already working on it but I don't know. And on my own I'm no developer so i am not able to fix it or to find a solution for that.

**Comment by Quibus-burst** [comment]
Best practice for now is to upgrade from a 1.3.6cg wallet or to sync from scratch with 2.0.1
Once the db is upgraded you cannot roll back to 1.3.6cg

**Comment by Ready2Burst** [comment]
@Quibus-burst I've been dead in the water for a week unfortunately. See https://github.com/PoC-Consortium/burstcoin/issues/181#issuecomment-374937576

**Comment by Quibus-burst** [comment]
a week? Then you are still on 2.0 bransh with broken DB i suppose.

**Comment by Ready2Burst** [comment]
Ah, yes. Was confused about the release timing. Just picked up 2.0.1 and unfortunately have to resync from the beginning. See y'all in a few days!

**Comment by ChrisMaroglou** [comment]
Last night my wallet got stuck at height 473220 (i see many nodes on burst explorer stuck at this height) and console showed a "Block not accepted - Double Spending transaction" exception. 
This morning i rolled back the chain 100 blocks and resynced successfully.

**Comment by BurnMe2** [comment]
Hi,

resync is going fine for me. But after resyncing immediatly the wallet gets stuck on the last Block. It's showing "Block not accepted". The blockchain downloading is running fine but after synching it alway got stuck.

How do you rolled back the chain 100 blocks ? (I am using Linux).

**Comment by ChrisMaroglou** [comment]
I used Qbundle windows for popOff. On Linux i guess you'd have to first set "API.Debug = on" in brs.properties then start the wallet and go to [http://localhost:8125/test?requestTag=DEBUG](http://localhost:8125/test?requestTag=DEBUG) where you do "clearUnconfirmedTransactions" first and then "popOff". I am not sure this is the safest way though, correct me anyone if i am wrong.

**Comment by Quibus-burst** [comment]
Did a popoff resolve the issue?

**Comment by ChrisMaroglou** [comment]
For the time being yes, but it might get stuck on a future block.

**Comment by Quibus-burst** [comment]
Please upgrade to v2.0.2 now. (no db resync required) this should prevent further stuckness of this kind.

**Comment by krispipeleers** [comment]
That indeed fixed my problems today.

**Comment by BurnMe2** [comment]
I upgraded to BRS 2.0.2 and downloaded blockchain from scratch but it stucks again with the message "Block not accepted" at Block 473581. Stil the same issue like in the other Versions.

Try to pop off with Linux and tell you the results

**Comment by cgebe** [comment]
@BurnMe2 `Block not accepted` is another issue - https://github.com/PoC-Consortium/burstcoin/issues/208
I am closing this issue in regard to the different one.
